name: Build and Release WPF Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet publish ScreenProtector/ScreenProtector.csproj --configuration Release --output ./publish --runtime win-x64 --self-contained false

    - name: Compress artifacts
      run: Compress-Archive -Path ./publish/* -DestinationPath ./ScreenProtector-win-x64.zip -Force

    - name: Create Release
      if: github.event_name == 'push'
      id: create_release
      uses: peter-evans/create-release@v6
      with:
        tag: v${{ github.sha }}
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      if: github.event_name == 'push'
      uses: peter-evans/upload-release-asset@v2
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        file: ./ScreenProtector-win-x64.zip
        asset_name: ScreenProtector-win-x64.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
